name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # BACKEND (.NET)
      # -----------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore solution
        run: dotnet restore asisya-smart-assistance.sln

      - name: Build solution
        run: dotnet build asisya-smart-assistance.sln --no-restore -c Release

      - name: Run tests
        run: dotnet test asisya-smart-assistance.sln --no-build -c Release
        continue-on-error: true

      # -----------------------------
      # FRONTEND
      # -----------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: |
          cd frontend/provider-ui
          npm install

      - name: Build frontend
        working-directory: frontend/provider-ui
        run: |
          npm ci
          npm run build
      # -----------------------------
      # DOCKER
      # -----------------------------
      - name: Build Docker images
        run: docker compose build